os: linux
dist: focal
language: python
python:
  - 3.7
  - 3.8
  - "3.9-dev"
before_install:
  - pip install --upgrade pip
  - python setup.py install
  - pip install "nbconvert==5.6.1"
  - pip install coverage[toml] coveralls flake8 pytest-cov innerscope sympy
before_script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
script: pytest --cov-report term --cov
after_success: coveralls
